services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./export:/app/export
    ports:
      - 3000:3000
    container_name: mirror-what
    restart: unless-stopped